/**
 * Perguntas frequentes — fonte única compartilhada pela seção visual (FAQ.tsx)
 * e pelo dado estruturado FAQPage (JSON-LD), para o Google renderizar as
 * perguntas como rich snippet sem duplicar o conteúdo.
 */
export const FAQ_ITEMS: [question: string, answer: string][] = [
  ['O VentureERP serve para metalúrgica e moveleira de qualquer porte?', 'Sim. Atendemos desde a serralheria/marcenaria que está saindo da planilha até grupos industriais com várias plantas. O sistema é o mesmo software de produção sob medida, com plano de corte, ficha técnica e Bloco K — o que muda é o escopo de módulos e usuários. Comece pela demonstração em /demo para ver na sua realidade.'],
  ['Como funciona o plano de corte (nesting) de chapa e MDF?', 'Você cadastra a peça na ficha técnica e o sistema gera automaticamente o melhor aproveitamento da chapa de aço ou da placa de MDF, mostrando a sobra antes de cortar. Na prática, é menos retalho virando lixo e menos compra de material. Costuma ser o módulo que se paga mais rápido.'],
  ['Vocês calculam o custo real por peça e por ordem de produção?', 'Sim. O custo puxa material (pela ficha técnica), processo (dobra, solda, usinagem, pintura, fitas, ferragens) e mão de obra apontada pelo operador. Você sabe a margem de cada peça no ato do orçamento e o custo real acumulado enquanto a ordem de produção roda — não só no fechamento do mês.'],
  ['O sistema gera o Bloco K e o SPED da indústria?', 'Gera. Como o consumo de matéria-prima e a produção ficam registrados no próprio sistema, o Bloco K (livro de produção e estoque) e o SPED Fiscal saem automaticamente, dentro do prazo. Nossa equipe fiscal acompanha as mudanças da Receita e dos SEFAZs — você não descobre obrigação nova pelo noticiário.'],
  ['Qual a diferença entre a demonstração gravada e a ao vivo?', 'A demonstração gravada (/demo) são vídeos curtos por módulo — orçamento, plano de corte, ordem de produção, fiscal — que você assiste no seu ritmo, sem falar com vendedor. A ao vivo é personalizada: um especialista do seu setor mostra o sistema com cenários da sua fábrica e responde em tempo real. Recomendamos ver a gravada primeiro e depois agendar a ao vivo em /agendar.'],
  ['Como é a migração sem parar a produção?', 'Nosso time importa o cadastro de produtos, as fichas técnicas, clientes, estoque e histórico. Validamos tudo em paralelo ao seu sistema atual e só fazemos o cutover com sua aprovação. A fábrica não para, nenhum dado se perde. A média é 30 dias do contrato ao chão de fábrica operando.'],
  ['Qual a estrutura de suporte depois da implantação?', 'Suporte via chat, e-mail e WhatsApp em horário comercial, com um CSM que entende de produção — não um atendente lendo script. O nível de acompanhamento (revisões periódicas, SLA em contrato, diretor de conta) é definido junto com você conforme o porte da operação.'],
  ['Quanto custa o VentureERP?', 'O preço depende do porte da fábrica, do número de usuários e dos módulos que fazem sentido para a sua operação — por isso não publicamos tabela. Montamos a proposta depois da primeira reunião, quando já entendemos como você produz. Assim você recebe um número real, não uma faixa que muda no contrato.'],
];
